### ISSUE TITLE
Python 3 compatibility?

### ISSUE THREAD

**Issue by alphaparrot** [ddbkoll/PyRADS-shortwave#2]
Have all components been fully-verified to be working for Python 3? I run into many issues trying to build PyRADS in Python 3.6.5 on Ubuntu, specifically the DISORT wrapper, such as Python 2 print statements in installation scripts, and upon converting a number of files with 2to3, get the following error: 
```
Traceback (most recent call last):
  File "test_disort.py", line 9, in <module>
    import disort
  File "/home/USER/anaconda3/lib/python3.6/site-packages/disort/__init__.py", line 9, in <module>
    from . import _disort
ImportError: /home/USER/anaconda3/lib/python3.6/site-packages/disort/_disort.so: invalid ELF header
```
Any ideas, slash additional info on compatibility?

**Comment by brian-rose** [comment]
We converted the non-scattering version of PyRADS to Python 3 compatibility here: https://github.com/ddbkoll/PyRADS/pull/9

It looks like the Python code in `PyRADS-shortwave/pyDISORT-master/` similarly needs just a little bit of updating to print and import statements.

**Comment by brian-rose** [comment]
Looks like there is a Python 3 version of the pyDISORT code here: https://github.com/Devilox96/PyDisort3.5

But looks incomplete?

**Comment by danielkoll** [comment]
@alphaparrot , I've tried adapting the pyDISORT wrapper for python3. See here: https://github.com/ddbkoll/PyDISORT3. The rest of PyRADS-SW still needs to be adapted to match the changes @brian-rose and others made to PyRADS-LW.
